<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<Protobuf Include="Protos/*.proto" Type="Both" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Consul" Version="1.7.14.9" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
	  <ProjectReference Include="..\OnlineStore\OnlineStore.CustomerService.csproj" />
  </ItemGroup>

</Project>
